# https://github.com/jekyll/minima
theme: minima


minima:
  # Generate social links in footer.
  social_links:
    - { platform: github,         user_url: "https://github.com/blakefren" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/blakefrench" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/7215238/blake-french" }
